include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - lib/*.g.dart
    - lib/**/*.g.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: false  # Agree in theory, should get rid of those print() calls
    avoid_escaping_inner_quotes: false
    avoid_positional_boolean_parameters: false  # Agree in theory
    avoid_redundant_argument_values: false  # Building body parts is nicer
    lines_longer_than_80_chars: true
    missing_whitespace_between_adjacent_strings: false  # Storyline has this
    prefer_null_aware_method_calls: false  # Forces you to use `.call()`
    prefer_if_elements_to_conditional_expressions: false  # I like ternary more
    prefer_final_locals: false  # Verbose
    prefer_single_quotes: false  # Way too painful when using normal English.
    require_trailing_commas: false  # Agree in theory, should fix
    unnecessary_raw_strings: false  # It seem safer to raw some strings
    use_function_type_syntax_for_parameters: false  # Agree in theory
