sdk:
 - stable

stages:
  - analyze:
    - analyze: --fatal-infos --fatal-warnings .
    - format
  - unit_test:
    - test

#        - dartanalyzer: --fatal-infos --fatal-warnings .
#  - build:
#    - command: pub run build_runner build --delete-conflicting-outputs
#      - command: pub run test -t long-running --run-skipped
